import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { SiteShell } from "@/components/SiteShell";
import { LocaleProvider } from "@/components/LocaleProvider";
import "./globals.css";

// A fresh CSP nonce is generated by middleware for every document request.
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
	title: {
		default: "N4cht4r4 · Community Garden",
		template: "%s · N4cht4r4",
	},
	description: "Nachtaras Community Garden für Streams, Turniere, Challenges, gemeinsame Spielprojekte und Community-Kunst.",
	icons: {
		icon: [
			{ url: "/favicon.svg", type: "image/svg+xml" },
			{ url: "/favicon.png", type: "image/png" },
		],
	},
	openGraph: {
		title: "N4cht4r4 · Community Garden",
		description: "Streams, Turniere, Challenges und Community-Projekte unter Kirschblüten.",
		type: "website",
	},
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="de" suppressHydrationWarning data-scroll-behavior="smooth">
			<SessionProvider refetchInterval={0} refetchOnWindowFocus={false} refetchWhenOffline={false}>
				<LocaleProvider>
					<SiteShell>{children}</SiteShell>
				</LocaleProvider>
			</SessionProvider>
		</html>
	);
}
